---
abstract: 'Build your distributions like SCHWIGON does'
author:
  - 'Steffen Schwigon <ss5@renormalist.net>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-SCHWIGON
requires:
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::EOLTests: 0.02
  Dist::Zilla::Plugin::Git::Describe: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaResources: 3
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::StaticVersion: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::PluginBundle::Classic: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::PluginBundle::Git::CheckFor: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Method::Signatures::Simple: 0
  Moose: 1.00
  Moose::Util::TypeConstraints: 0
  MooseX::Types::Email: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0.20
  MooseX::Types::URI: 0
  Pod::Weaver::PluginBundle::SCHWIGON: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-SCHWIGON
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-SCHWIGON
  repository: git://github.com/renormalist/Dist-Zilla-PluginBundle-SCHWIGON.git
version: 0.010
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@SCHWIGON/@Basic/GatherDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@SCHWIGON/@Basic/PruneCruft'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@SCHWIGON/@Basic/ManifestSkip'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@SCHWIGON/@Basic/MetaYAML'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::License
      name: '@SCHWIGON/@Basic/License'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@SCHWIGON/@Basic/Readme'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@SCHWIGON/@Basic/ExtraTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@SCHWIGON/@Basic/ExecDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@SCHWIGON/@Basic/ShareDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@SCHWIGON/@Basic/MakeMaker'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@SCHWIGON/@Basic/Manifest'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@SCHWIGON/@Basic/TestRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@SCHWIGON/@Basic/ConfirmRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@SCHWIGON/@Basic/UploadToCPAN'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@SCHWIGON/MetaConfig'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@SCHWIGON/MetaJSON'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@SCHWIGON/PkgVersion'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@SCHWIGON/PodSyntaxTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@SCHWIGON/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@SCHWIGON/PodCoverageTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@SCHWIGON/MetaResources'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@SCHWIGON/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@SCHWIGON/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@SCHWIGON/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@SCHWIGON/AutoPrereqs'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@SCHWIGON/Git::Describe'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@SCHWIGON/CheckChangesHasContent'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@SCHWIGON/NextRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@SCHWIGON/Git::CheckFor::CorrectBranch'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@SCHWIGON/Git::NextVersion'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@SCHWIGON/@Git/Check'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@SCHWIGON/@Git/Commit'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@SCHWIGON/@Git/Tag'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@SCHWIGON/@Git/Push'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300020
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300020
x_authority: cpan:SCHWIGON
